version: 0.1
phases:
  install:
    commands:
      - npm install ask-sdk
      - npm install cheerio-httpcli
      - npm install request-promise
      - aws cloudformation package --template-file template.yaml --s3-bucket alexa-skill-roprice 
                                   --output-template-file output-template.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - output-template.yaml