AWSTemplateFormatVersion: '2010-09-09'
Description: sample
Resources:
  SamSample:
    Properties:
      CodeUri: s3://alexa-skill-roprice/7b482a0ca4d2e83844a70dc3e2ff3f9a
      Handler: index.handler
      Role: arn:aws:iam::176973848769:role/lambda_basic_execution
      Runtime: nodejs8.10
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
